name: Unit Tests

on:
  push:
    # only trigger on branches, not on tags
    branches: 'develop'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.11'
            cache: 'pip' # caching pip stuff
    - name: Run Install Swirl
      run: ./install.sh
    - name: Run Install Tests Swirl
      run: ./install-test.sh
    - name: Run pytest unit tests
      run: pytest
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
